/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cn.edu.yuntukeji.finacing.view1;

import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import cn.edu.yuntukeji.finacing.controller.Dispacher;
import cn.edu.yuntukeji.finacing.view1.pulus.CustomerComboBox;
import cn.edu.yuntukeji.finacing.view1.pulus.DateChooserJButton;
import cn.edu.yuntukeji.finacing.view1.pulus.SaleManComboBox;
import net.sf.json.JSONObject;

/**
 * 
 * @author Administrator
 */
public class DeliveryInformationFrame extends javax.swing.JFrame {
	
	private Dispacher dp;
	private static DeliveryInformationFrame deliveryInformationFrame = null;
	/**
	 * Creates new form DeliveryInformationFrame
	 */
	private DeliveryInformationFrame() {
		 dp = new Dispacher();
		initComponents();
	}
public static DeliveryInformationFrame getInstance(){
	if(deliveryInformationFrame == null){
		deliveryInformationFrame = new DeliveryInformationFrame();
	}
	
	((SaleManComboBox) txtSalesMan).initModel();
	txtSalesMan.updateUI();

	((CustomerComboBox) comboCutomer).initModel();
	comboCutomer.updateUI();
	return deliveryInformationFrame;
}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		txtDeliveryID = new javax.swing.JTextField();
		txtDeliveryAddress = new javax.swing.JTextField();
		txtSalesMan = new SaleManComboBox();
		comboCutomer = new CustomerComboBox();
		xyDeliveryDate = new DateChooserJButton();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		lblSum = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jLabel9 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblProductDetail = new javax.swing.JTable();
		btnAdd = new javax.swing.JButton();
		btnupdate = new javax.swing.JButton();
		btnDel = new javax.swing.JButton();
		jLabel10 = new javax.swing.JLabel();
		btnSave = new javax.swing.JButton();
		btnReturn = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("销售单信息");

		jLabel1.setForeground(new java.awt.Color(255, 51, 0));
		jLabel1.setText("销售单号：");

		jLabel2.setText("销售日期：");

		jLabel3.setText("客 户 ：");

		jLabel4.setText("送货地址：");

		jLabel5.setText("销售员：");

		txtDeliveryID.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtDeliveryIDActionPerformed(evt);
			}
		});

		txtDeliveryAddress
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						txtDeliveryAddressActionPerformed(evt);
					}
				});

//		txtSalesMan.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
//				"1", "2", "3", "4" }));

//		comboCutomer.setModel(new javax.swing.DefaultComboBoxModel(
//				new String[] { "1", "2", "3", "4" }));
		comboCutomer.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				comboCutomerActionPerformed(evt);
			}
		});
		tblProductDetail.addFocusListener(new FocusAdapter() {
			@Override
			public void focusLost(FocusEvent e) {
				if(tblProductDetail.getValueAt(tblProductDetail.getSelectedRow(), 2)!=null&&tblProductDetail.getValueAt(tblProductDetail.getSelectedRow(), 3)!=null)
				{
				Float price = Float.parseFloat((String) tblProductDetail.getValueAt(tblProductDetail.getSelectedRow(), 2));
				Float quantity =Float.parseFloat((String) tblProductDetail.getValueAt(tblProductDetail.getSelectedRow(), 3));
				tblProductDetail.setValueAt(price*quantity, tblProductDetail.getSelectedRow(), 4);
				}
				Float total = 0.0f;
				for (int i = 0; i < tblProductDetail.getRowCount(); i++) {
					if(tblProductDetail.getValueAt(i, 4)!=null){
					total +=(Float) tblProductDetail.getValueAt(i, 4);
					}
				}
				lblSum.setText(""+total);
			}
		});
		jLabel6.setText("总金额：");

		jLabel7.setText("￥");

		lblSum.setText("0.00");

		jLabel9.setForeground(new java.awt.Color(255, 51, 0));
		jLabel9.setText("销售商品明细");

		tblProductDetail.setModel(new javax.swing.table.DefaultTableModel(
				null, new String[] {
						"商品编号", "商品名称", "单价", "数量", "金额" }) {
			boolean[] canEdit = new boolean[] { true, true, true, true,
					false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(tblProductDetail);

		btnAdd.setText("增加");
		btnAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAddActionPerformed(evt);
			}
		});

		btnupdate.setText("修改");
		btnupdate.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnupdateActionPerformed(evt);
			}
		});

		btnDel.setText("删除");
		btnDel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDelActionPerformed(evt);
			}
		});

		jLabel10.setForeground(new java.awt.Color(255, 51, 0));
		jLabel10.setText("注意：红色字体项目为必填！");

		btnSave.setText("保存");
		btnSave.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSaveActionPerformed(evt);
			}
		});

		btnReturn.setText("返回");
		btnReturn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnReturnActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel9)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel10)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												314,
																												Short.MAX_VALUE)
																										.addComponent(
																												btnSave))))
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																519,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								btnReturn)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												btnAdd)
																										.addContainerGap()))
																		.addGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				jPanel1Layout
																						.createSequentialGroup()
																						.addComponent(
																								btnupdate)
																						.addContainerGap()))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				btnDel)
																		.addContainerGap()))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				btnSave)
																		.addComponent(
																				btnReturn))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel9)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jScrollPane1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								182,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												btnAdd)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												btnupdate)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												btnDel)))
																		.addGap(34,
																				34,
																				34)
																		.addComponent(
																				jLabel10)))
										.addContainerGap(20, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGap(20, 20, 20)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(
														jPanel1,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel1)
																				.addComponent(
																						jLabel3)
																				.addComponent(
																						jLabel2))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																								.addComponent(
																										txtDeliveryID)
																								.addComponent(
																										comboCutomer,
																										0,
																										216,
																										Short.MAX_VALUE))
																				.addComponent(
																						xyDeliveryDate,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						144,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel4)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										txtDeliveryAddress))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel6)
																								.addGap(18,
																										18,
																										18)
																								.addComponent(
																										lblSum)
																								.addGap(158,
																										158,
																										158)
																								.addComponent(
																										jLabel7))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel5)
																								.addGap(18,
																										18,
																										18)
																								.addComponent(
																										txtSalesMan,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										240,
																										javax.swing.GroupLayout.PREFERRED_SIZE)))))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(jLabel5)
												.addComponent(
														txtDeliveryID,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														txtSalesMan,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel4)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		jLabel3)
																.addComponent(
																		comboCutomer,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(
																		txtDeliveryAddress,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(xyDeliveryDate)
												.addComponent(jLabel6)
												.addComponent(lblSum)
												.addComponent(jLabel7))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void comboCutomerActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comboCutomerActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_comboCutomerActionPerformed

	private void txtDeliveryIDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtDeliveryIDActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtDeliveryIDActionPerformed

	private void txtDeliveryAddressActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtDeliveryAddressActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtDeliveryAddressActionPerformed

	private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDelActionPerformed
		Float total = 0.0f;
		for (int i = 0; i < tblProductDetail.getRowCount(); i++) {
			if(tblProductDetail.getValueAt(i, 4)!=null){
			total +=(Float) tblProductDetail.getValueAt(i, 4);
			}
		}
		lblSum.setText(""+total);
		DefaultTableModel model= (DefaultTableModel) tblProductDetail.getModel();
		if(tblProductDetail.getSelectedRow()!=-1){
		model.removeRow(tblProductDetail.getSelectedRow());
		
		tblProductDetail.updateUI();
		}
		

		
	}// GEN-LAST:event_btnDelActionPerformed

	private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddActionPerformed
		//
		
		
		
		DefaultTableModel model= (DefaultTableModel) tblProductDetail.getModel();
		
		model.addRow(new Vector<>());
		

		
	}// GEN-LAST:event_btnAddActionPerformed

	private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnupdateActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnupdateActionPerformed

	private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSaveActionPerformed
		
		
		Map<String, Object> request1 = new HashMap<>();
		request1.put("url", "DeliveryMaster/save");
	
		Map<String,Object> date1  = new HashMap<>();
		if(!txtDeliveryID.getText().equals("")){
		date1.put("deliveryId", Integer.parseInt(txtDeliveryID.getText()));
		
		Map<String,Object> salesManId  = new HashMap<>();
		salesManId.put("salesMamId", txtSalesMan.getSelectedItem());
		
		
		Map<String,Object> customerId  = new HashMap<>();
		
		customerId.put("id", comboCutomer.getSelectedItem());
		
		date1.put("salesManId", salesManId);
		date1.put("customerId", customerId);
		
		date1.put("deliveryAddress", txtDeliveryAddress.getText());
		SimpleDateFormat sdf =   new SimpleDateFormat("yyyy-MM-dd");
		try {
			date1.put("deliveryDate", sdf.parse(xyDeliveryDate.getText()).getTime());
		} catch (ParseException e) {
			e.printStackTrace();
		}
		date1.put("subTotal",Float.parseFloat(lblSum.getText()));
		
		request1.put("data", date1);
		
		dp.execute(request1);
		
		//爆粗子表
		
		
		
		TableModel model = tblProductDetail.getModel();
		
		for(int i = 0;i<model.getRowCount();i++){
			
			if(txtDeliveryID.getText()!=null&&tblProductDetail.getValueAt(i, 2)!=null&&tblProductDetail.getValueAt(i, 3)!=null){
			Map<String, Object> request = new HashMap<>();
			request.put("url", "DeliveryDetail/save");
			Map<String,Object> date  = new HashMap<>();
			Map<String,Object> dm  = new HashMap<>();
			dm.put("deliveryId",Integer.parseInt(txtDeliveryID.getText()));
			date.put("deliveryId",dm);
			Map<String,Object> product  = new HashMap<>();
			product.put("productId", tblProductDetail.getValueAt(i, 0));
			product.put("productName", tblProductDetail.getValueAt(i, 1));
			SimpleDateFormat sdf1 =   new SimpleDateFormat("yyyy-MM-dd");
			try {
			product.put("lastDeliveryDate", sdf1.parse(xyDeliveryDate.getText()).getTime());
			} catch (ParseException e) {
				e.printStackTrace();
			}
			date.put("productId", product);
			Float price = Float.parseFloat((String) tblProductDetail.getValueAt(i, 2));
			Float quantity =Float.parseFloat((String) tblProductDetail.getValueAt(i, 3));
			date.put("salesUnitPrice",price);
			date.put("salesQuantity", -quantity);
			date.put("salesAmount", -price*quantity);
			request.put("data", date);
			
			dp.execute(request);
			}
			
		}
		
		
		}
		DeliveryFrame.sysnView();
		dispose();
		
	}// GEN-LAST:event_btnSaveActionPerformed

	private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnReturnActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnReturnActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(
					DeliveryInformationFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(
					DeliveryInformationFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(
					DeliveryInformationFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(
					DeliveryInformationFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new DeliveryInformationFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAdd;
	private javax.swing.JButton btnDel;
	private javax.swing.JButton btnReturn;
	private javax.swing.JButton btnSave;
	private javax.swing.JButton btnupdate;
	private static javax.swing.JComboBox comboCutomer;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lblSum;
	private javax.swing.JTable tblProductDetail;
	private javax.swing.JTextField txtDeliveryAddress;
	private javax.swing.JTextField txtDeliveryID;
	private static javax.swing.JComboBox txtSalesMan;
	private javax.swing.JButton xyDeliveryDate;
	// End of variables declaration//GEN-END:variables
}
