package cn.edu.yuntukeji.finacing.view1;

import javax.swing.JOptionPane;

import cn.edu.yuntukeji.finacing.controller.Dispacher;

/**
 * 
 * @author HP-Developer
 */
public class LoginFrame extends javax.swing.JFrame {
	private Dispacher dp;
	private static LoginFrame loginFrame = null;
	/**
	 * Creates new form LoginFrame
	 */
	private LoginFrame() {
		 dp = new Dispacher();
		initComponents();
	}
public static LoginFrame getInstance(){
	if(loginFrame == null){
		loginFrame = new LoginFrame();
	}
	return loginFrame;
}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		name = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		txtUserName = new javax.swing.JTextField();
		btnSubmint = new javax.swing.JButton();
		btnReset = new javax.swing.JButton();
		txtPassword = new javax.swing.JPasswordField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("登录");

		name.setText("用户名");

		jLabel2.setText("密  码");

		txtUserName.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtUserNameActionPerformed(evt);
			}
		});

		btnSubmint.setText("提交");
		btnSubmint.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSubmintActionPerformed(evt);
			}
		});

		btnReset.setText("重置");
		btnReset.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnResetActionPerformed(evt);
			}
		});

		txtPassword.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				txtPasswordActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(70, 70,
																		70)
																.addComponent(
																		btnSubmint)
																.addGap(33, 33,
																		33)
																.addComponent(
																		btnReset))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(62, 62,
																		62)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						jLabel2,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						51,
																						Short.MAX_VALUE)
																				.addComponent(
																						name,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE))
																.addGap(18, 18,
																		18)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						txtUserName,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						184,
																						Short.MAX_VALUE)
																				.addComponent(
																						txtPassword))))
								.addContainerGap(85, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap(50, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														name,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														33,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														txtUserName,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														jLabel2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														36,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														txtPassword,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(btnSubmint)
												.addComponent(btnReset))
								.addGap(112, 112, 112)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtUserNameActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtUserNameActionPerformed

	private void btnSubmintActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSubmintActionPerformed
		String userName = txtUserName.getText(); // 获取用户名文本
		char[] chPassword = txtPassword.getPassword();// 获取用户密码文本
		String strPassword = new String(chPassword);
		if (!userName.equals("") && !strPassword.equals("")) {
			if (userName.equals("admin") && strPassword.equals("admin")) { // 和数据库中的用户名和密码比较，验证信息
				System.out.println("登录成功");
				MainFrame m = MainFrame.getInstance();
				m.setVisible(true);
				m.toFront();
				this.dispose();

			} else {
				JOptionPane.showMessageDialog(rootPane, "用户名或密码不正确，请重新输入!",
						"提示", WIDTH);
				txtUserName.setText("");
				txtPassword.setText("");
			}
		} else {
			System.out.println("用户名或密码不完整！！！");
			JOptionPane.showMessageDialog(rootPane, "用户名或密码不完整!", "提示", WIDTH);
			txtUserName.setText("");
			txtPassword.setText("");
		}

	}// GEN-LAST:event_btnSubmintActionPerformed

	private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnResetActionPerformed
		txtUserName.setText("");
		txtPassword.setText("");
	}// GEN-LAST:event_btnResetActionPerformed

	private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtPasswordActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_txtPasswordActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LoginFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnReset;
	private javax.swing.JButton btnSubmint;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel name;
	private javax.swing.JPasswordField txtPassword;
	private javax.swing.JTextField txtUserName;
	// End of variables declaration//GEN-END:variables
}
