/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.edu.yuntukeji.finacing.view1;

import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import cn.edu.yuntukeji.finacing.controller.Dispacher;
import cn.edu.yuntukeji.finacing.view1.pulus.DateChooserJButton;
import cn.edu.yuntukeji.finacing.view1.pulus.SupplierComboBox;

/**
 * 
 * @author Administrator
 */
public class PurchaseRefundInformationFrame extends javax.swing.JFrame {
	private Dispacher dp;
	private static PurchaseRefundInformationFrame  purchaseRefundInformationFrame = null;
	/**
	 * Creates new form PurchaseRefundInformationFrame
	 */
	private PurchaseRefundInformationFrame() {
		 dp = new Dispacher();
		initComponents();
	}
public static PurchaseRefundInformationFrame getInstance(){
	if(purchaseRefundInformationFrame == null){
		purchaseRefundInformationFrame = new PurchaseRefundInformationFrame();
	}
	((SupplierComboBox) comboSupplier).initModel();
	comboSupplier.updateUI();
	return purchaseRefundInformationFrame;
}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		txtPurchaseRefundID = new javax.swing.JTextField();
		xyRefundDate = new DateChooserJButton();
		lblSum = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		comboSupplier = new SupplierComboBox();
		jLabel7 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblPurchaseRefundInformation = new javax.swing.JTable();
		btnAdd = new javax.swing.JButton();
		btnDel = new javax.swing.JButton();
		btnUpdate = new javax.swing.JButton();
		jLabel8 = new javax.swing.JLabel();
		btnSave = new javax.swing.JButton();
		btnReturn = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("采购退货单信息");

		jLabel1.setForeground(new java.awt.Color(255, 0, 0));
		jLabel1.setText("采购退货单号：");

		jLabel2.setText("退 货 日 期 ：");

		jLabel3.setText("总金额：");

		jLabel4.setText("供应商：");

		lblSum.setText("0.00");

		jLabel6.setText("￥");
		jLabel7.setForeground(new java.awt.Color(255, 51, 0));
		jLabel7.setText("采购退货商品明细");
		tblPurchaseRefundInformation.addFocusListener(new FocusAdapter() {
			@Override
			public void focusLost(FocusEvent e) {
				if(tblPurchaseRefundInformation.getValueAt(tblPurchaseRefundInformation.getSelectedRow(), 2)!=null&&tblPurchaseRefundInformation.getValueAt(tblPurchaseRefundInformation.getSelectedRow(), 3)!=null)
				{
				Float price = Float.parseFloat((String) tblPurchaseRefundInformation.getValueAt(tblPurchaseRefundInformation.getSelectedRow(), 2));
				Float quantity =Float.parseFloat((String) tblPurchaseRefundInformation.getValueAt(tblPurchaseRefundInformation.getSelectedRow(), 3));
				tblPurchaseRefundInformation.setValueAt(price*quantity, tblPurchaseRefundInformation.getSelectedRow(), 4);
				}
				Float total = 0.0f;
				for (int i = 0; i < tblPurchaseRefundInformation.getRowCount(); i++) {
					if(tblPurchaseRefundInformation.getValueAt(i, 4)!=null){
					total +=(Float) tblPurchaseRefundInformation.getValueAt(i, 4);
					}
				}
				lblSum.setText(""+total);
			}
		});
		tblPurchaseRefundInformation
				.setModel(new javax.swing.table.DefaultTableModel(
						null,
						new String[] { "商品编号", "商品名称", "单价", "数量", "金额" }) {
					boolean[] canEdit = new boolean[] { true, true, true,
							true, false };

					public boolean isCellEditable(int rowIndex, int columnIndex) {
						return canEdit[columnIndex];
					}
				});
		jScrollPane1.setViewportView(tblPurchaseRefundInformation);

		btnAdd.setText("增加");
		btnAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAddActionPerformed(evt);
			}
		});

		btnDel.setText("删除");
		btnDel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDelActionPerformed(evt);
			}
		});

		btnUpdate.setText("更新");
		btnUpdate.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnUpdateActionPerformed(evt);
			}
		});

		jLabel8.setForeground(new java.awt.Color(255, 51, 0));
		jLabel8.setText("注意：红色字体项目为必填！");

		btnSave.setText("保存");
		btnSave.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSaveActionPerformed(evt);
			}
		});

		btnReturn.setText("返回");
		btnReturn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnReturnActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(19, 19, 19)
								.addComponent(jLabel8)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE).addComponent(btnSave)
								.addGap(17, 17, 17).addComponent(btnReturn)
								.addContainerGap())
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(20, 20,
																		20)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel2)
																				.addComponent(
																						jLabel1))
																.addGap(18, 18,
																		18)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						txtPurchaseRefundID,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						132,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						xyRefundDate,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						132,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(46, 46,
																		46)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel4)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										comboSupplier,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										139,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel3)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(
																										lblSum)
																								.addGap(97,
																										97,
																										97)
																								.addComponent(
																										jLabel6))))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(20, 20,
																		20)
																.addComponent(
																		jLabel7))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jScrollPane1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		433,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																								.addComponent(
																										btnAdd)
																								.addComponent(
																										btnUpdate,
																										javax.swing.GroupLayout.Alignment.TRAILING))
																				.addComponent(
																						btnDel,
																						javax.swing.GroupLayout.Alignment.TRAILING))))
								.addGap(0, 0, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		jLabel1)
																.addComponent(
																		txtPurchaseRefundID,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		jLabel4)
																.addComponent(
																		comboSupplier,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel2)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		xyRefundDate)
																.addComponent(
																		jLabel3)
																.addComponent(
																		lblSum)
																.addComponent(
																		jLabel6)))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jLabel7)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														182,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		btnAdd)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		btnUpdate)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		btnDel)))
								.addGap(32, 32, 32)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel8)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		btnSave)
																.addComponent(
																		btnReturn)))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddActionPerformed
		
		
		DefaultTableModel model= (DefaultTableModel) tblPurchaseRefundInformation.getModel();
		
		model.addRow(new Vector<>());
		
	}// GEN-LAST:event_btnAddActionPerformed

	private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUpdateActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnUpdateActionPerformed

	private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDelActionPerformed
	
		Float total = 0.0f;
		for (int i = 0; i < tblPurchaseRefundInformation.getRowCount(); i++) {
			if(tblPurchaseRefundInformation.getValueAt(i, 4)!=null){
			total +=(Float) tblPurchaseRefundInformation.getValueAt(i, 4);
			}
		}
		lblSum.setText(""+total);
		DefaultTableModel model= (DefaultTableModel) tblPurchaseRefundInformation.getModel();
		if(tblPurchaseRefundInformation.getSelectedRow()!=-1){
		model.removeRow(tblPurchaseRefundInformation.getSelectedRow());
		
		tblPurchaseRefundInformation.updateUI();
		}
		
	}// GEN-LAST:event_btnDelActionPerformed

	private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSaveActionPerformed
		

		Map<String, Object> request1 = new HashMap<>();
		request1.put("url", "PurchaseMaster/save");
	
		Map<String,Object> date1  = new HashMap<>();
		if(!txtPurchaseRefundID.getText().equals("")){
		date1.put("purchaseId", Integer.parseInt(txtPurchaseRefundID.getText()));
		
		Map<String,Object> supplierId  = new HashMap<>();
		supplierId.put("supplierId", comboSupplier.getSelectedItem());
		
		
		
		date1.put("supplierId", supplierId);
		
		
		date1.put("subTotal", lblSum.getText());
		SimpleDateFormat sdf =   new SimpleDateFormat("yyyy-MM-dd");
		try {
			date1.put("purchaseDate", sdf.parse(xyRefundDate.getText()).getTime());
		} catch (ParseException e) {
			e.printStackTrace();
		}
		date1.put("purchaseProperty", -1);
		
		request1.put("data", date1);
		
		dp.execute(request1);
		
		//爆粗子表
		
		
		
		TableModel model = tblPurchaseRefundInformation.getModel();
		
		for(int i = 0;i<model.getRowCount();i++){
			
			if(txtPurchaseRefundID.getText()!=null&&tblPurchaseRefundInformation.getValueAt(i, 2)!=null&&tblPurchaseRefundInformation.getValueAt(i, 3)!=null){
			Map<String, Object> request = new HashMap<>();
			request.put("url", "PurchaseDetail/save");
			Map<String,Object> date  = new HashMap<>();
			Map<String,Object> dm  = new HashMap<>();
			dm.put("purchaseId",Integer.parseInt(txtPurchaseRefundID.getText()));
			date.put("purchaseId",dm);
			Map<String,Object> product  = new HashMap<>();
			product.put("productId", tblPurchaseRefundInformation.getValueAt(i, 0));
			product.put("productName", tblPurchaseRefundInformation.getValueAt(i, 1));
			SimpleDateFormat sdf1 =   new SimpleDateFormat("yyyy-MM-dd");
			try {
			product.put("lastDeliveryDate", sdf1.parse(xyRefundDate.getText()).getTime());
			} catch (ParseException e) {
				e.printStackTrace();
			}
			date.put("productId", product);
			Float price = Float.parseFloat((String) tblPurchaseRefundInformation.getValueAt(i, 2));
			Float quantity =Float.parseFloat((String) tblPurchaseRefundInformation.getValueAt(i, 3));
			date.put("purchaseUnitPrice",price);
			date.put("purchaseQuantity", -quantity);
			date.put("purchaseAmount", -price*quantity);
			
			request.put("data", date);
			
			dp.execute(request);
			}
			
		}
		
		
		}
		
		
		PurchaseRefundFrame.sysnView();
		dispose();
		
	}// GEN-LAST:event_btnSaveActionPerformed

	private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnReturnActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnReturnActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(
					PurchaseRefundInformationFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(
					PurchaseRefundInformationFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(
					PurchaseRefundInformationFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(
					PurchaseRefundInformationFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PurchaseRefundInformationFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAdd;
	private javax.swing.JButton btnDel;
	private javax.swing.JButton btnReturn;
	private javax.swing.JButton btnSave;
	private javax.swing.JButton btnUpdate;
	private javax.swing.ButtonGroup buttonGroup1;
	private static javax.swing.JComboBox comboSupplier;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lblSum;
	private javax.swing.JTable tblPurchaseRefundInformation;
	private javax.swing.JTextField txtPurchaseRefundID;
	private javax.swing.JButton xyRefundDate;
	// End of variables declaration//GEN-END:variables
}
