/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.edu.yuntukeji.finacing.view1;

import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import cn.edu.yuntukeji.finacing.controller.Dispacher;
import cn.edu.yuntukeji.finacing.view1.pulus.CustomerComboBox;
import cn.edu.yuntukeji.finacing.view1.pulus.DateChooserJButton;
import cn.edu.yuntukeji.finacing.view1.pulus.SaleManComboBox;
import cn.edu.yuntukeji.finacing.view1.pulus.SupplierComboBox;

/**
 * 
 * @author Administrator
 */
public class PurchaseInformationFrame extends javax.swing.JFrame {
	private Dispacher dp;
	private static PurchaseInformationFrame purchaseInformationFrame = null;
	/**
	 * Creates new form PurchaseInformationFrame
	 */
	private PurchaseInformationFrame() {
		 dp = new Dispacher();
		initComponents();
	}
public static PurchaseInformationFrame getInstance(){
	if(purchaseInformationFrame == null){
		purchaseInformationFrame = new PurchaseInformationFrame();
	}
	
	((SupplierComboBox) comboSupplier).initModel();
	comboSupplier.updateUI();
	return purchaseInformationFrame;
}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		txtPurchaseID = new javax.swing.JTextField();
		comboSupplier = new SupplierComboBox();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		xyPurchaseDate = new DateChooserJButton();
		lblSum = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jLabel7 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblPurchaseInformation = new javax.swing.JTable();
		btnAdd = new javax.swing.JButton();
		btnDel = new javax.swing.JButton();
		btnUpdate = new javax.swing.JButton();
		jLabel8 = new javax.swing.JLabel();
		btnSave = new javax.swing.JButton();
		btnReturn = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("采购单信息");

		jLabel1.setForeground(new java.awt.Color(255, 0, 0));
		jLabel1.setText("采购单号：");

		jLabel2.setText("采购日期：");

		jLabel3.setText("供货商");



		jLabel4.setText("总金额：");

		jLabel5.setText("￥");

		lblSum.setText("0.00");

		jLabel7.setForeground(new java.awt.Color(255, 0, 0));
		jLabel7.setText("采购商品明细");

		tblPurchaseInformation
				.setModel(new javax.swing.table.DefaultTableModel(
						null,
						new String[] { "商品编号", "商品名称", "单价", "数量", "金额" }) {
					boolean[] canEdit = new boolean[] { true, true, true,
							true, false };

					public boolean isCellEditable(int rowIndex, int columnIndex) {
						return canEdit[columnIndex];
					}
				});
		jScrollPane1.setViewportView(tblPurchaseInformation);

		btnAdd.setText("增加");
		btnAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAddActionPerformed(evt);
			}
		});

		btnDel.setText("删除");
		btnDel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDelActionPerformed(evt);
			}
		});

		btnUpdate.setText("更新");
		btnUpdate.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnUpdateActionPerformed(evt);
			}
		});
		tblPurchaseInformation.addFocusListener(new FocusAdapter() {
			@Override
			public void focusLost(FocusEvent e) {
				if(tblPurchaseInformation.getValueAt(tblPurchaseInformation.getSelectedRow(), 2)!=null&&tblPurchaseInformation.getValueAt(tblPurchaseInformation.getSelectedRow(), 3)!=null)
				{
				Float price = Float.parseFloat((String) tblPurchaseInformation.getValueAt(tblPurchaseInformation.getSelectedRow(), 2));
				Float quantity =Float.parseFloat((String) tblPurchaseInformation.getValueAt(tblPurchaseInformation.getSelectedRow(), 3));
				tblPurchaseInformation.setValueAt(price*quantity, tblPurchaseInformation.getSelectedRow(), 4);
				}
				Float total = 0.0f;
				for (int i = 0; i < tblPurchaseInformation.getRowCount(); i++) {
					if(tblPurchaseInformation.getValueAt(i, 4)!=null){
					total +=(Float) tblPurchaseInformation.getValueAt(i, 4);
					}
				}
				lblSum.setText(""+total);
			}
		});
		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jLabel7))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				607,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								btnUpdate)
																						.addComponent(
																								btnDel)
																						.addComponent(
																								btnAdd))))
										.addContainerGap(16, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel7)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				0,
																				Short.MAX_VALUE)
																		.addContainerGap())
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(15,
																				15,
																				15)
																		.addComponent(
																				btnAdd)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				btnUpdate)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				btnDel)
																		.addContainerGap(
																				90,
																				Short.MAX_VALUE)))));

		jLabel8.setForeground(new java.awt.Color(255, 0, 0));
		jLabel8.setText("注意：红色字体为必填项！");

		btnSave.setText("保存");
		btnSave.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSaveActionPerformed(evt);
			}
		});

		btnReturn.setText("返回");
		btnReturn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnReturnActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel1)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(
																										txtPurchaseID,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										202,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel2)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(
																										xyPurchaseDate,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										Short.MAX_VALUE)))
																.addGap(32, 32,
																		32)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel3)
																								.addGap(18,
																										18,
																										18)
																								.addComponent(
																										comboSupplier,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										275,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel4)
																								.addGap(18,
																										18,
																										18)
																								.addComponent(
																										lblSum)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										Short.MAX_VALUE)
																								.addComponent(
																										jLabel5)))
																.addContainerGap(
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel8)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(
																		btnSave)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		btnReturn)
																.addGap(15, 15,
																		15)))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(19, 19, 19)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														txtPurchaseID,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel3)
												.addComponent(
														comboSupplier,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(16, 16, 16)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(xyPurchaseDate)
												.addComponent(jLabel4)
												.addComponent(lblSum)
												.addComponent(jLabel5))
								.addGap(18, 18, 18)
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel8)
												.addComponent(btnSave)
												.addComponent(btnReturn))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddActionPerformed
	
	DefaultTableModel model= (DefaultTableModel) tblPurchaseInformation.getModel();
		
		model.addRow(new Vector<>());
		
		
	}// GEN-LAST:event_btnAddActionPerformed

	private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUpdateActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnUpdateActionPerformed

	private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDelActionPerformed
		
		Float total = 0.0f;
		for (int i = 0; i < tblPurchaseInformation.getRowCount(); i++) {
			if(tblPurchaseInformation.getValueAt(i, 4)!=null){
			total +=(Float) tblPurchaseInformation.getValueAt(i, 4);
			}
		}
		lblSum.setText(""+total);
		DefaultTableModel model= (DefaultTableModel) tblPurchaseInformation.getModel();
		if(tblPurchaseInformation.getSelectedRow()!=-1){
		model.removeRow(tblPurchaseInformation.getSelectedRow());
		
		tblPurchaseInformation.updateUI();
		}
		


		
	}// GEN-LAST:event_btnDelActionPerformed

	private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSaveActionPerformed
		

		
		Map<String, Object> request1 = new HashMap<>();
		request1.put("url", "PurchaseMaster/save");
	
		Map<String,Object> date1  = new HashMap<>();
		if(!txtPurchaseID.getText().equals("")){
		date1.put("purchaseId", Integer.parseInt(txtPurchaseID.getText()));
		
		Map<String,Object> supplierId  = new HashMap<>();
		supplierId.put("supplierId", comboSupplier.getSelectedItem());
		
		
		
		date1.put("supplierId", supplierId);
		
		
		date1.put("subTotal", lblSum.getText());
		SimpleDateFormat sdf =   new SimpleDateFormat("yyyy-MM-dd");
		try {
			date1.put("purchaseDate", sdf.parse(xyPurchaseDate.getText()).getTime());
		} catch (ParseException e) {
			e.printStackTrace();
		}
		
		request1.put("data", date1);
		
		dp.execute(request1);
		
		//爆粗子表
		
		
		
		TableModel model = tblPurchaseInformation.getModel();
		
		for(int i = 0;i<model.getRowCount();i++){
			
			if(txtPurchaseID.getText()!=null&&tblPurchaseInformation.getValueAt(i, 2)!=null&&tblPurchaseInformation.getValueAt(i, 3)!=null){
			Map<String, Object> request = new HashMap<>();
			request.put("url", "PurchaseDetail/save");
			Map<String,Object> date  = new HashMap<>();
			Map<String,Object> dm  = new HashMap<>();
			dm.put("purchaseId",Integer.parseInt(txtPurchaseID.getText()));
			date.put("purchaseId",dm);
			Map<String,Object> product  = new HashMap<>();
			product.put("productId", tblPurchaseInformation.getValueAt(i, 0));
			product.put("productName", tblPurchaseInformation.getValueAt(i, 1));
			SimpleDateFormat sdf1 =   new SimpleDateFormat("yyyy-MM-dd");
			try {
			product.put("lastPurchaseDate", sdf1.parse(xyPurchaseDate.getText()).getTime());
			} catch (ParseException e) {
				e.printStackTrace();
			}
			date.put("productId", product);
			Float price = Float.parseFloat((String) tblPurchaseInformation.getValueAt(i, 2));
			Float quantity =Float.parseFloat((String) tblPurchaseInformation.getValueAt(i, 3));
			date.put("purchaseUnitPrice",price);
			date.put("purchaseQuantity", quantity);
			date.put("purchaseAmount", price*quantity);
			request.put("data", date);
			
			dp.execute(request);
			}
			
		}
		//更新仓库
		
		
		
		}
		
		PurchaseFrame.sysnView();
		
		this.dispose();
	}// GEN-LAST:event_btnSaveActionPerformed

	private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnReturnActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnReturnActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(
					PurchaseInformationFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(
					PurchaseInformationFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(
					PurchaseInformationFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(
					PurchaseInformationFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new PurchaseInformationFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAdd;
	private javax.swing.JButton btnDel;
	private javax.swing.JButton btnReturn;
	private javax.swing.JButton btnSave;
	private javax.swing.JButton btnUpdate;
	private static javax.swing.JComboBox comboSupplier;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lblSum;
	private javax.swing.JTable tblPurchaseInformation;
	private javax.swing.JTextField txtPurchaseID;
	private javax.swing.JButton xyPurchaseDate;
	// End of variables declaration//GEN-END:variables
}
