/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.edu.yuntukeji.finacing.view1;

import java.util.HashMap;
import java.util.Map;

import cn.edu.yuntukeji.finacing.controller.Dispacher;
import net.sf.json.JSONArray;
import net.sf.json.JSONObject;

/**
 *
 * @author Administrator
 */
public class SaleRefundFrame extends javax.swing.JFrame {
	private static Dispacher dp;
	private static SaleRefundFrame saleRefundFrame = null;
    /**
     * Creates new form SaleRefundFrame
     */
    private SaleRefundFrame() {
    	 dp = new Dispacher();
        initComponents();
    }
public static SaleRefundFrame getInstance(){
	if(saleRefundFrame == null){
		saleRefundFrame = new SaleRefundFrame();
	}
	return saleRefundFrame;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSaleDetail = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSaleRefund = new javax.swing.JTable();
        Object[][] o = findAllDate();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("销售退货单管理");

        tblSaleDetail.setModel(new javax.swing.table.DefaultTableModel(
            null,
            new String [] {
                "商品编号", "商品名称", "单价", "数量", "金额"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSaleDetail);

        jLabel2.setText("销售单明细一览");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnAdd.setText("增加");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("更新");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDel.setText("删除");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        tblSaleRefund.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        btnExit.setText("退出");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel1.setText("销售退货单一览");

        tblSaleRefund.setModel(new javax.swing.table.DefaultTableModel(
         o,
            new String [] {
                "销售退货单", "销售员", "销售日期", "客户", "客户地址", "总金额"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSaleRefund);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(btnDel)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit)
                        .addGap(23, 23, 23)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnExit)
                    .addComponent(btnDel)
                    .addComponent(btnUpdate))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static Object[][] findAllDate() {
		
    	
    	Map<String, Object> request = new HashMap<>();
    	request.put("url", "DeliveryMaster/queryGodownProduct");	
		Map<String, Object> reMap = dp.execute(request);
		JSONArray json = JSONArray.fromObject(reMap.get("result"));
		System.out.println(json);
		
		Object [][] o = new Object [json.size()][6];
		for (int i = 0;i<json.size();i++) {
			// "销售退货单", "销售员", "销售日期", "客户", "客户地址", "总金额"
			o[i][0] = ((JSONObject)json.get(i)).getString("deliveryId");
			JSONObject deliveryDate =((JSONObject)json.get(i)).getJSONObject("deliveryDate");
			if(!deliveryDate.isEmpty()){
				o[i][2] = deliveryDate.getString("year")+"-"+deliveryDate.getString("month")+"-"+deliveryDate.getString("day");
				//o[i][5] =deliveryDate.getString("year")+"-"+deliveryDate.getString("month")+"-"+deliveryDate.getString("day");
			}
			
			o[i][1]= ((JSONObject)json.get(i)).getJSONObject("salesManId").getString("chineseName");
			o[i][3]= ((JSONObject)json.get(i)).getJSONObject("customerId").getString("customerName");
			o[i][4]= ((JSONObject)json.get(i)).getJSONObject("customerId").getString("cutomerAddress");
			o[i][5] = ((JSONObject)json.get(i)).getString("subTotal");
			
	
			}
		
		return o;
		
	}

	private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       
		SaleRefundDetailFrame sdf = SaleRefundDetailFrame.getInstance();
		sdf.setVisible(true);
		sdf.toFront();
		
		
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
       

    	
    	Map<String, Object> request = new HashMap<>();
		request.put("url", "DeliveryMaster/removeById/"+tblSaleRefund.getValueAt(tblSaleRefund.getSelectedRow(),0));	
		Map<String, Object> reMap = dp.execute(request);
		JSONObject json = JSONObject.fromObject(reMap.get("result"));
		 Object[][] o = findAllDate();
		 tblSaleRefund.setModel(new javax.swing.table.DefaultTableModel(
		            o,
		            new String [] {
		                "销售订单号", "销售员", "订单日期", "客户", "总金额", "送货地址", "是否出库", "出库日期"
		            }
		        ) {
		            boolean[] canEdit = new boolean [] {
		                false, false, false, false, false, false, false, false
		            };

		            public boolean isCellEditable(int rowIndex, int columnIndex) {
		                return canEdit [columnIndex];
		            }
		        });
		 tblSaleRefund.updateUI();
    	
    	
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed
    public static void  sysnView(){
    	tblSaleRefund.setModel(new javax.swing.table.DefaultTableModel(
    	         findAllDate(),
    	            new String [] {
    	                "销售退货单", "销售员", "销售日期", "客户", "客户地址", "总金额"
    	            }
    	        ) {
    	            boolean[] canEdit = new boolean [] {
    	                false, false, false, false, false, false
    	            };

    	            public boolean isCellEditable(int rowIndex, int columnIndex) {
    	                return canEdit [columnIndex];
    	            }
    	        });
    	tblSaleRefund.updateUI();
    }
private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {  
    	
    	Map<String, Object> request = new HashMap<>();
		request.put("url", "DeliveryDetail/findDeliveryDetailBydeliveryId");	
		Map<String,Object> salersMan  = new HashMap<>();
		salersMan.put("deliveryId", Integer.parseInt((String) tblSaleRefund.getValueAt(tblSaleRefund.getSelectedRow(),0)));
		request.put("param", salersMan);
		Map<String, Object> reMap = dp.execute(request);
		JSONArray json = JSONArray.fromObject(reMap.get("result"));
		System.out.println(json);
		Object [][] traderInfo= new Object[json.size()][5];
		for (int i = 0; i < json.size(); i++) {
					JSONObject	productId = ((JSONObject)json.get(i)).getJSONObject("productId");
					if(!productId.isEmpty()){
						traderInfo[i][0] = productId.getString("productId");
						traderInfo[i][1] = productId.getString("productName");
					}
					traderInfo[i][2] = ((JSONObject)json.get(i)).getString("salesUnitPrice");
					traderInfo[i][3] = ((JSONObject)json.get(i)).getString("salesQuantity");
					traderInfo[i][4] = ((JSONObject)json.get(i)).getString("salesAmount");
		}
		tblSaleDetail.setModel(new javax.swing.table.DefaultTableModel(
				 traderInfo,
		            new String [] {
		                "商品编号", "商品名称", "单价", "数量", "金额"
		            }
		        ));
		tblSaleDetail.updateUI();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleRefundFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleRefundFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleRefundFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleRefundFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaleRefundFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblSaleDetail;
    private static  javax.swing.JTable tblSaleRefund;
    // End of variables declaration//GEN-END:variables
}
