/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package cn.edu.yuntukeji.finacing.view1;

import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import cn.edu.yuntukeji.finacing.controller.Dispacher;
import cn.edu.yuntukeji.finacing.view1.pulus.CustomerComboBox;
import cn.edu.yuntukeji.finacing.view1.pulus.DateChooserJButton;
import cn.edu.yuntukeji.finacing.view1.pulus.SaleManComboBox;

/**
 * 
 * @author Administrator
 */
public class SaleRefundDetailFrame extends javax.swing.JFrame {
	private Dispacher dp;
	private static SaleRefundDetailFrame saleRefundDetailFrame = null;

	/**
	 * Creates new form SaleRefundDetailFrame
	 */
	private SaleRefundDetailFrame() {
		dp = new Dispacher();
		initComponents();
	}

	public static SaleRefundDetailFrame getInstance() {
		if (saleRefundDetailFrame == null) {
			saleRefundDetailFrame = new SaleRefundDetailFrame();
		}

		((SaleManComboBox) comboSalesMan).initModel();
		comboSalesMan.updateUI();
		
		((CustomerComboBox) comboCustomer).initModel();
		comboCustomer.updateUI();
		return saleRefundDetailFrame;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		txtDeliveryRefundID = new javax.swing.JTextField();
		txtCustomerAddress = new javax.swing.JTextField();
		comboSalesMan = new SaleManComboBox();
		comboCustomer = new CustomerComboBox();
		xyRefundDate = new DateChooserJButton();
		jLabel7 = new javax.swing.JLabel();
		lblSum = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jLabel9 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblSaleRefundDetail = new javax.swing.JTable();
		btnAdd = new javax.swing.JButton();
		btnUpdate = new javax.swing.JButton();
		btnDel = new javax.swing.JButton();
		btnSave = new javax.swing.JButton();
		btnReturn = new javax.swing.JButton();
		jLabel10 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("销售退货单信息");

		jLabel1.setText("总金额：");

		jLabel2.setForeground(new java.awt.Color(255, 0, 0));
		jLabel2.setText("销售退货单号：");

		jLabel3.setText("客     户   ：");

		jLabel4.setText("销售员：");

		jLabel5.setText("退 货 日 期 ：");

		jLabel6.setText("客户地址：");

		tblSaleRefundDetail.addFocusListener(new FocusAdapter() {
			@Override
			public void focusLost(FocusEvent e) {
				if (tblSaleRefundDetail.getValueAt(
						tblSaleRefundDetail.getSelectedRow(), 2) != null
						&& tblSaleRefundDetail.getValueAt(
								tblSaleRefundDetail.getSelectedRow(), 3) != null) {
					Float price = Float.parseFloat((String) tblSaleRefundDetail
							.getValueAt(tblSaleRefundDetail.getSelectedRow(), 2));
					Float quantity = Float
							.parseFloat((String) tblSaleRefundDetail
									.getValueAt(tblSaleRefundDetail
											.getSelectedRow(), 3));
					tblSaleRefundDetail.setValueAt(price * quantity,
							tblSaleRefundDetail.getSelectedRow(), 4);
				}
				Float total = 0.0f;
				for (int i = 0; i < tblSaleRefundDetail.getRowCount(); i++) {
					if (tblSaleRefundDetail.getValueAt(i, 4) != null) {
						total += (Float) tblSaleRefundDetail.getValueAt(i, 4);
					}
				}
				lblSum.setText("" + total);
			}
		});
//		comboSalesMan.setModel(new javax.swing.DefaultComboBoxModel(
//				new String[] { "1", "2", "3", "4" }));

//		comboCustomer.setModel(new javax.swing.DefaultComboBoxModel(
//				new String[] { "1", "2", "3", "4" }));
		

		jLabel7.setText("￥");

		lblSum.setText("0.00");

		jLabel9.setForeground(new java.awt.Color(255, 0, 0));
		jLabel9.setText("销售退货商品明细");

		tblSaleRefundDetail.setModel(new javax.swing.table.DefaultTableModel(
				null, new String[] { "商品编号", "商品名称", "单价", "数量", "金额" }) {
			boolean[] canEdit = new boolean[] { true, true, true, true, false };

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane1.setViewportView(tblSaleRefundDetail);

		btnAdd.setText("增加");
		btnAdd.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnAddActionPerformed(evt);
			}
		});

		btnUpdate.setText("更新");
		btnUpdate.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnUpdateActionPerformed(evt);
			}
		});

		btnDel.setText("删除");
		btnDel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnDelActionPerformed(evt);
			}
		});

		btnSave.setText("保存");
		btnSave.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSaveActionPerformed(evt);
			}
		});

		btnReturn.setText("返回");
		btnReturn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnReturnActionPerformed(evt);
			}
		});

		jLabel10.setForeground(new java.awt.Color(255, 51, 0));
		jLabel10.setText("注意：红色字体项目为必填！");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel9)
																		.addGap(0,
																				0,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				474,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								btnDel,
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								btnUpdate,
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								btnAdd,
																								javax.swing.GroupLayout.Alignment.TRAILING))))
										.addContainerGap())
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addGap(18, 18, 18)
										.addComponent(jLabel10)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(btnSave)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(btnReturn)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addComponent(jLabel9)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																182,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				btnAdd)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				btnUpdate)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				btnDel)))
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								btnReturn)
																						.addComponent(
																								btnSave))
																		.addContainerGap())
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				jLabel10)
																		.addContainerGap(
																				20,
																				Short.MAX_VALUE)))));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(19, 19, 19)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel3)
												.addComponent(jLabel2)
												.addComponent(jLabel5))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														comboCustomer,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														156,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														txtDeliveryRefundID,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														156,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														xyRefundDate,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														156,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(13, 13, 13)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(
																		layout.createSequentialGroup()
																				.addGap(39,
																						39,
																						39)
																				.addComponent(
																						jLabel4))
																.addGroup(
																		javax.swing.GroupLayout.Alignment.TRAILING,
																		layout.createSequentialGroup()
																				.addGap(27,
																						27,
																						27)
																				.addComponent(
																						jLabel6)))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGap(39, 39,
																		39)
																.addComponent(
																		jLabel1)))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														comboSalesMan,
														0,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		lblSum)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(
																		jLabel7))
												.addComponent(
														txtCustomerAddress))
								.addContainerGap())
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jPanel1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(14, 14,
																		14)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel4)
																				.addComponent(
																						comboSalesMan,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(14, 14,
																		14))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addContainerGap()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel2)
																				.addComponent(
																						txtDeliveryRefundID,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(9, 9, 9)))
								.addGap(1, 1, 1)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																												.addComponent(
																														jLabel6)
																												.addComponent(
																														txtCustomerAddress,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGap(16,
																										16,
																										16))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.BASELINE)
																												.addComponent(
																														jLabel3)
																												.addComponent(
																														comboCustomer,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGap(21,
																										21,
																										21)))
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel1)
																				.addComponent(
																						lblSum)
																				.addComponent(
																						jLabel7))
																.addGap(28, 28,
																		28))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						xyRefundDate)
																				.addComponent(
																						jLabel5))
																.addGap(26, 26,
																		26)))
								.addComponent(jPanel1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSaveActionPerformed
		Map<String, Object> request1 = new HashMap<>();
		request1.put("url", "DeliveryMaster/save");

		Map<String, Object> date1 = new HashMap<>();
		if (!txtDeliveryRefundID.getText().equals("")) {
			date1.put("deliveryId",
					Integer.parseInt(txtDeliveryRefundID.getText()));

			Map<String, Object> salesManId = new HashMap<>();
			salesManId.put("salesMamId", comboSalesMan.getSelectedItem());

			Map<String, Object> customerId = new HashMap<>();

			customerId.put("id", comboCustomer.getSelectedItem());

			date1.put("salesManId", salesManId);
			date1.put("customerId", customerId);

			date1.put("deliveryAddress", txtCustomerAddress.getText());
			SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
			try {
				date1.put("deliveryDate", sdf.parse(xyRefundDate.getText())
						.getTime());
			} catch (ParseException e) {
				e.printStackTrace();
			}
			date1.put("subTotal", Float.parseFloat(lblSum.getText()));

			date1.put("deliveryProperty", -1);
			request1.put("data", date1);

			dp.execute(request1);

			// 爆粗子表

			TableModel model = tblSaleRefundDetail.getModel();

			for (int i = 0; i < model.getRowCount(); i++) {

				if (txtDeliveryRefundID.getText() != null
						&& tblSaleRefundDetail.getValueAt(i, 2) != null
						&& tblSaleRefundDetail.getValueAt(i, 3) != null) {
					Map<String, Object> request = new HashMap<>();
					request.put("url", "DeliveryDetail/save");
					Map<String, Object> date = new HashMap<>();
					Map<String, Object> dm = new HashMap<>();
					dm.put("deliveryId",
							Integer.parseInt(txtDeliveryRefundID.getText()));
					date.put("deliveryId", dm);
					Map<String, Object> product = new HashMap<>();
					product.put("productId",
							tblSaleRefundDetail.getValueAt(i, 0));
					product.put("productName",
							tblSaleRefundDetail.getValueAt(i, 1));
					SimpleDateFormat sdf1 =   new SimpleDateFormat("yyyy-MM-dd");
					try {
					product.put("lastDeliveryDate", sdf1.parse(xyRefundDate.getText()).getTime());
					} catch (ParseException e) {
						e.printStackTrace();
					}
					date.put("productId", product);
					Float price = Float.parseFloat((String) tblSaleRefundDetail
							.getValueAt(i, 2));
					Float quantity = Float
							.parseFloat((String) tblSaleRefundDetail
									.getValueAt(i, 3));
					date.put("salesUnitPrice", price);
					date.put("salesQuantity", quantity);
					date.put("salesAmount", price * quantity);
					request.put("data", date);

					dp.execute(request);
				}

			}

		}

		SaleRefundFrame.sysnView();
		dispose();

	}// GEN-LAST:event_btnSaveActionPerformed

	private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddActionPerformed

		DefaultTableModel model = (DefaultTableModel) tblSaleRefundDetail
				.getModel();

		model.addRow(new Vector<>());

	}// GEN-LAST:event_btnAddActionPerformed

	private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUpdateActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnUpdateActionPerformed

	private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDelActionPerformed

		Float total = 0.0f;
		for (int i = 0; i < tblSaleRefundDetail.getRowCount(); i++) {
			if (tblSaleRefundDetail.getValueAt(i, 4) != null) {
				total += (Float) tblSaleRefundDetail.getValueAt(i, 4);
			}
		}
		lblSum.setText("" + total);
		DefaultTableModel model = (DefaultTableModel) tblSaleRefundDetail
				.getModel();
		if (tblSaleRefundDetail.getSelectedRow() != -1) {
			model.removeRow(tblSaleRefundDetail.getSelectedRow());

			tblSaleRefundDetail.updateUI();
		}

	}// GEN-LAST:event_btnDelActionPerformed

	private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnReturnActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnReturnActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(
					SaleRefundDetailFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(
					SaleRefundDetailFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(
					SaleRefundDetailFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(
					SaleRefundDetailFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new SaleRefundDetailFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAdd;
	private javax.swing.JButton btnDel;
	private javax.swing.JButton btnReturn;
	private javax.swing.JButton btnSave;
	private javax.swing.JButton btnUpdate;
	private static javax.swing.JComboBox comboCustomer;
	private static javax.swing.JComboBox comboSalesMan;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel lblSum;
	private javax.swing.JTable tblSaleRefundDetail;
	private javax.swing.JTextField txtCustomerAddress;
	private javax.swing.JTextField txtDeliveryRefundID;
	private javax.swing.JButton xyRefundDate;
	// End of variables declaration//GEN-END:variables
}
